---
- hosts: mywebserver
  become : yes
  tasks:
  - name : i want to insatll java on ubuntu nodes
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat nodes
    yum: 
     name : "{{myjavapackonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"