---
- hosts: 172.31.23.40
  become: yes
  vars: 
   myvars1: git
   myvars2: tree
   myvars3: wget
  tasks:
  - name: i want to display variable 
    debug: 
      msg: "{{myvars1}}"

  - name: i want to install git
    apt:
     name: "{{ item }}"
     state: present
    loop:
      - "{{myvars1}}"
      - "{{myvars2}}"
      - "{{myvars3}}"

      