---

- hosts: 172.31.23.40
  become: yes
  tasks:
  - name: i want install git
    apt: 
     name: apache2
     state: present
    tags: mygit

  - name: i want install tree
    apt: 
     name: tree
     state: present
    tags: mytree

  - name: i want install wget
    apt: 
     name: wget
     state: present
    tags: myywget
