---
# tasks file for mywebrole

- name: i want to install apache2
  apt: 
    name: apache2
    state: present
  notify: webserverrestart

- name: i want to copy index file to nodes
  template:
   src: template/myindex.j2
   dest: /var/www/html/index.html
  notify: webserverrestart